language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-18
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - platform-tools
  - build-tools-23.0.2
  - android-23
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

  # Additional components
  - extra-android-m2repository
  - extra-google-m2repository
script:
  - ./gradlew build testDebugUnitTestCoverage
